### ISSUE TITLE
zsh에서도 alias 등록

### ISSUE THREAD

**Issue by wicksome** [wicksome/ahd#1]

**Comment by kkd927** [comment]
혹시 쉘 종류에 의존적이지 않게 /etc/profile 에 설정하면 더 좋지 않을까요?!

**Comment by kkd927** [comment]
저게 될련지는 모르겠네요.. ㅎㅎ....

**Comment by wicksome** [comment]
쉘에 의존적이지 않도록 npm으로 publish 했어요
예전엔 bash_profile에 ahd를 alias 등록했는데,
`sudo npm install -g ahd`하면 bin 파일이 등록되네요.
근데 실행할때 `sudo ahd`를 항상 쳐야한다는게 문제...
