### ISSUE TITLE
설치 스크립트

### ISSUE THREAD

**Issue by kkd927** [wicksome/ahd#6]
개인적으로 설치 스크립트가 있었으면 좋겠습니다! ㅎㅎ
- 깃 클론
- node 가 없으면 node 설치
- npm 설치 등등

**Comment by wicksome** [comment]
npm 패키지로 배포.

```bash
$ npm install -g ahd
$ sudo ahd init 
```

since:

https://github.com/wicksome/ahd/tree/v0.2.0
